services:
  nginx:
    image: nginx:1.28.0-alpine3.21
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - web

  web:
    image: registry.digitalocean.com/djangoapp-registry/mydjangoapp:9330c09dac17cf380fb2315a47c5663d
    restart: unless-stopped
    command: gunicorn mydjangoapp.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env #kyiv3